/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationmedecinclient;

import patientRemote.Patient;

/**
 *
 * @author Nicolas
 */
public class analysesFrame extends javax.swing.JFrame {

    Patient patient;
    
    /**
     * Creates new form analysesFrame
     */
    public analysesFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public analysesFrame(Patient pat) {
        initComponents();
        this.setLocationRelativeTo(null);
        patient = pat;
        patientLabel.setText(patient.getNom() + " " + patient.getPrenom());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        patientLabel = new javax.swing.JLabel();
        informationsJPanel = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        ana10Label = new javax.swing.JLabel();
        ana6Label1 = new javax.swing.JLabel();
        ana1Label1 = new javax.swing.JLabel();
        ana2Label1 = new javax.swing.JLabel();
        ana3Label1 = new javax.swing.JLabel();
        ana7Label = new javax.swing.JLabel();
        ana4Label1 = new javax.swing.JLabel();
        ana8Label = new javax.swing.JLabel();
        ana5Label1 = new javax.swing.JLabel();
        ana9Label = new javax.swing.JLabel();
        leutocytesLabel = new javax.swing.JLabel();
        hematiesLabel = new javax.swing.JLabel();
        hemoglobineLabel = new javax.swing.JLabel();
        hematocritesLabel = new javax.swing.JLabel();
        vgmLabel = new javax.swing.JLabel();
        ccmhLabel = new javax.swing.JLabel();
        tcmhLabel = new javax.swing.JLabel();
        vihLabel = new javax.swing.JLabel();
        globulesBlancLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        globulesBlancLab = new javax.swing.JLabel();
        ana6Label = new javax.swing.JLabel();
        ana1Label = new javax.swing.JLabel();
        ana2Label = new javax.swing.JLabel();
        ana3Label = new javax.swing.JLabel();
        tcmhLab = new javax.swing.JLabel();
        ana4Label = new javax.swing.JLabel();
        vihLab = new javax.swing.JLabel();
        ana5Label = new javax.swing.JLabel();
        rdwLab = new javax.swing.JLabel();
        leucocytesCB = new javax.swing.JCheckBox();
        hematiesCB = new javax.swing.JCheckBox();
        hemoglobineCB = new javax.swing.JCheckBox();
        hematocritesCB = new javax.swing.JCheckBox();
        vgmCB = new javax.swing.JCheckBox();
        ccmhCB = new javax.swing.JCheckBox();
        tcmhCB = new javax.swing.JCheckBox();
        vihCB = new javax.swing.JCheckBox();
        rdwCB = new javax.swing.JCheckBox();
        globulesBlancCB = new javax.swing.JCheckBox();
        newAnalyseButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nomLabel = new javax.swing.JLabel();
        prenomLabel = new javax.swing.JLabel();
        adresseLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        modifyButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        patientLabel.setText("nom patient");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        ana10Label.setText("jLabel12");

        ana6Label1.setText("C.C.M.H :");

        ana1Label1.setText("Leucocytes :");

        ana2Label1.setText("Hématies :");

        ana3Label1.setText("Hémoglobine :");

        ana7Label.setText("T.C.M.H :");

        ana4Label1.setText("Hématocrites :");

        ana8Label.setText("V.I.H :");

        ana5Label1.setText("V.G.M :");

        ana9Label.setText("Globules Blancs :");

        leutocytesLabel.setText("leutocytes");

        hematiesLabel.setText("hematies");

        hemoglobineLabel.setText("jLabel3");

        hematocritesLabel.setText("jLabel4");

        vgmLabel.setText("jLabel5");

        ccmhLabel.setText("jLabel6");

        tcmhLabel.setText("jLabel7");

        vihLabel.setText("jLabel8");

        globulesBlancLabel.setText("jLabel9");

        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ana6Label1)
                    .addComponent(ana5Label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vgmLabel)
                    .addComponent(ccmhLabel))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ana3Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ana2Label1)
                        .addComponent(ana1Label1))
                    .addComponent(ana4Label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hematocritesLabel)
                            .addComponent(hematiesLabel)
                            .addComponent(leutocytesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ana8Label, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ana7Label, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ana10Label, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(hemoglobineLabel)
                        .addGap(55, 55, 55)
                        .addComponent(ana9Label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tcmhLabel)
                    .addComponent(vihLabel)
                    .addComponent(globulesBlancLabel)
                    .addComponent(jLabel10))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana1Label1)
                    .addComponent(ana7Label)
                    .addComponent(leutocytesLabel)
                    .addComponent(tcmhLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana2Label1)
                    .addComponent(ana8Label)
                    .addComponent(hematiesLabel)
                    .addComponent(vihLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana3Label1)
                    .addComponent(ana9Label)
                    .addComponent(hemoglobineLabel)
                    .addComponent(globulesBlancLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana4Label1)
                    .addComponent(ana10Label)
                    .addComponent(hematocritesLabel)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana5Label1)
                    .addComponent(vgmLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana6Label1)
                    .addComponent(ccmhLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        informationsJPanel.addTab("Résultats", jPanel4);

        globulesBlancLab.setText("Globules blanc :");

        ana6Label.setText("C.C.M.H :");

        ana1Label.setText("Leucocytes :");

        ana2Label.setText("Hématies :");

        ana3Label.setText("Hémoglobine :");

        tcmhLab.setText("T.C.M.H :");

        ana4Label.setText("Hématocrites :");

        vihLab.setText("V.I.H :");

        ana5Label.setText("V.G.M :");

        rdwLab.setText("RDW :");

        hematocritesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hematocritesCBActionPerformed(evt);
            }
        });

        tcmhCB.setText("jCheckBox1");

        vihCB.setText("jCheckBox2");

        rdwCB.setText("jCheckBox3");

        globulesBlancCB.setText("jCheckBox4");

        newAnalyseButton.setText("Nouvelle Analyse");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ana3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ana6Label)
                        .addComponent(ana5Label)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ana2Label)
                                    .addComponent(ana1Label)))
                            .addComponent(ana4Label))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vgmCB)
                    .addComponent(hematocritesCB)
                    .addComponent(ccmhCB)
                    .addComponent(hemoglobineCB)
                    .addComponent(leucocytesCB)
                    .addComponent(hematiesCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newAnalyseButton)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tcmhLab, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vihLab, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdwLab, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(globulesBlancLab, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tcmhCB)
                            .addComponent(vihCB)
                            .addComponent(rdwCB)
                            .addComponent(globulesBlancCB))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana1Label)
                    .addComponent(tcmhLab)
                    .addComponent(leucocytesCB)
                    .addComponent(tcmhCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana2Label)
                    .addComponent(hematiesCB)
                    .addComponent(vihLab)
                    .addComponent(vihCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ana3Label)
                            .addComponent(hemoglobineCB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ana4Label)
                            .addComponent(hematocritesCB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ana5Label)
                            .addComponent(vgmCB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ana6Label)
                            .addComponent(ccmhCB)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdwLab)
                            .addComponent(rdwCB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(globulesBlancLab)
                            .addComponent(globulesBlancCB))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(newAnalyseButton))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        informationsJPanel.addTab("Analyses", jPanel1);

        nomLabel.setText("Nom :");

        prenomLabel.setText("Prenom :");

        adresseLabel.setText("Adresse :");

        modifyButton.setText("Modifier");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adresseLabel)
                    .addComponent(prenomLabel)
                    .addComponent(nomLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(modifyButton)
                .addGap(257, 257, 257))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomLabel)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenomLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresseLabel)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(modifyButton)
                .addContainerGap())
        );

        informationsJPanel.addTab("Informations", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(patientLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informationsJPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informationsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hematocritesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hematocritesCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hematocritesCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(analysesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(analysesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(analysesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(analysesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new analysesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresseLabel;
    private javax.swing.JLabel ana10Label;
    private javax.swing.JLabel ana1Label;
    private javax.swing.JLabel ana1Label1;
    private javax.swing.JLabel ana2Label;
    private javax.swing.JLabel ana2Label1;
    private javax.swing.JLabel ana3Label;
    private javax.swing.JLabel ana3Label1;
    private javax.swing.JLabel ana4Label;
    private javax.swing.JLabel ana4Label1;
    private javax.swing.JLabel ana5Label;
    private javax.swing.JLabel ana5Label1;
    private javax.swing.JLabel ana6Label;
    private javax.swing.JLabel ana6Label1;
    private javax.swing.JLabel ana7Label;
    private javax.swing.JLabel ana8Label;
    private javax.swing.JLabel ana9Label;
    private javax.swing.JCheckBox ccmhCB;
    private javax.swing.JLabel ccmhLabel;
    private javax.swing.JCheckBox globulesBlancCB;
    private javax.swing.JLabel globulesBlancLab;
    private javax.swing.JLabel globulesBlancLabel;
    private javax.swing.JCheckBox hematiesCB;
    private javax.swing.JLabel hematiesLabel;
    private javax.swing.JCheckBox hematocritesCB;
    private javax.swing.JLabel hematocritesLabel;
    private javax.swing.JCheckBox hemoglobineCB;
    private javax.swing.JLabel hemoglobineLabel;
    private javax.swing.JTabbedPane informationsJPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JCheckBox leucocytesCB;
    private javax.swing.JLabel leutocytesLabel;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton newAnalyseButton;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JLabel patientLabel;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JCheckBox rdwCB;
    private javax.swing.JLabel rdwLab;
    private javax.swing.JCheckBox tcmhCB;
    private javax.swing.JLabel tcmhLab;
    private javax.swing.JLabel tcmhLabel;
    private javax.swing.JCheckBox vgmCB;
    private javax.swing.JLabel vgmLabel;
    private javax.swing.JCheckBox vihCB;
    private javax.swing.JLabel vihLab;
    private javax.swing.JLabel vihLabel;
    // End of variables declaration//GEN-END:variables
}
