/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationmedecinclient;

import AnalyseRemote.AnalyseSBRemote;
import AnalyseRemote.Analyses;

import java.awt.Checkbox;
import java.util.Calendar;
import AnalyseRemote.Demande;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import patientRemote.Patient;
import patientRemote.patientSBRemote;

/**
 *
 * @author Nicolas
 */
public class analysesFrame extends javax.swing.JFrame {

    private static AnalyseSBRemote analyseSB;
    private static patientSBRemote patientSB;
    private Patient patient;
    private List<Analyses> listeAnalyses;
    private List<Analyses> a;
    
    /**
     * Creates new form analysesFrame
     */
    public analysesFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public analysesFrame(Patient pat, AnalyseSBRemote analyseBean, patientSBRemote patientBean) {
        try {
            Image image=(new javax.swing.ImageIcon(getClass().getResource("/Images/metal.jpg"))).getImage();
            this.setContentPane(new ImagePanel(image));
        } catch (Exception e) {
            e.printStackTrace();
        }
        this.pack();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setResizable(false);
       
        patient = pat;
        analyseSB = analyseBean;
        patientSB = patientBean;
        patientLabel.setText(patient.getNom() + " " + patient.getPrenom());
        
        DefaultListModel dlm = new DefaultListModel();//Model pour la liste des demandes
        listeAnalyses = new ArrayList<>();//Liste des analyses que l'on recoit
        a = new ArrayList<>();//Liste des analyses que l'on coche
        
        //Remplissage des informations du patient
        nomTF.setText(pat.getNom());
        prenomTF.setText(pat.getPrenom());
        adresseTF.setText(pat.getAdresse());
        
        //Remplissage de la liste de demandes pour le patient concerné
        List<Demande> d = analyseSB.getDemandesPatient(pat.getId());
        for(int i = 0; i < d.size(); i++)
        {
            dlm.addElement(d.get(i).getId() + "/" + d.get(i).getDateHeureDemande());
            demandesJList.setModel(dlm);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        patientLabel = new javax.swing.JLabel();
        informationsJPanel = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        demandesJList = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        ana6Label1 = new javax.swing.JLabel();
        ana1Label1 = new javax.swing.JLabel();
        ana2Label1 = new javax.swing.JLabel();
        ana3Label1 = new javax.swing.JLabel();
        ana7Label = new javax.swing.JLabel();
        ana4Label1 = new javax.swing.JLabel();
        ana8Label = new javax.swing.JLabel();
        ana5Label1 = new javax.swing.JLabel();
        ana9Label = new javax.swing.JLabel();
        leucocytesLabel = new javax.swing.JLabel();
        hematiesLabel = new javax.swing.JLabel();
        hemoglobineLabel = new javax.swing.JLabel();
        hematocritesLabel = new javax.swing.JLabel();
        vgmLabel = new javax.swing.JLabel();
        ccmhLabel = new javax.swing.JLabel();
        tcmhLabel = new javax.swing.JLabel();
        vihLabel = new javax.swing.JLabel();
        globulesBlancLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        analysesJPanel = new javax.swing.JPanel();
        globulesBlancLab = new javax.swing.JLabel();
        ana6Label = new javax.swing.JLabel();
        ana1Label = new javax.swing.JLabel();
        ana2Label = new javax.swing.JLabel();
        ana3Label = new javax.swing.JLabel();
        tcmhLab = new javax.swing.JLabel();
        ana4Label = new javax.swing.JLabel();
        vihLab = new javax.swing.JLabel();
        ana5Label = new javax.swing.JLabel();
        leucocytesCB = new javax.swing.JCheckBox();
        hematiesCB = new javax.swing.JCheckBox();
        hemoglobineCB = new javax.swing.JCheckBox();
        hematocritesCB = new javax.swing.JCheckBox();
        vgmCB = new javax.swing.JCheckBox();
        ccmhCB = new javax.swing.JCheckBox();
        tcmhCB = new javax.swing.JCheckBox();
        vihCB = new javax.swing.JCheckBox();
        globulesBlancCB = new javax.swing.JCheckBox();
        newAnalyseButton = new javax.swing.JButton();
        urgentRB = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        nomLabel = new javax.swing.JLabel();
        prenomLabel = new javax.swing.JLabel();
        adresseLabel = new javax.swing.JLabel();
        nomTF = new javax.swing.JTextField();
        prenomTF = new javax.swing.JTextField();
        adresseTF = new javax.swing.JTextField();
        modifyButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        patientLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        patientLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientLabel.setText("nom patient");

        demandesJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                demandesJListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(demandesJList);

        ana6Label1.setText("C.C.M.H :");

        ana1Label1.setText("Leucocytes :");

        ana2Label1.setText("Hématies :");

        ana3Label1.setText("Hémoglobine :");

        ana7Label.setText("T.C.M.H :");

        ana4Label1.setText("Hématocrites :");

        ana8Label.setText("V.I.H :");

        ana5Label1.setText("V.G.M :");

        ana9Label.setText("Globules Blancs :");

        leucocytesLabel.setText("-");

        hematiesLabel.setText("-");

        hemoglobineLabel.setText("-");

        hematocritesLabel.setText("-");

        vgmLabel.setText("-");

        ccmhLabel.setText("-");

        tcmhLabel.setText("-");

        vihLabel.setText("-");

        globulesBlancLabel.setText("-");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ana3Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ana4Label1)
                    .addComponent(ana2Label1)
                    .addComponent(ana1Label1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hemoglobineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hematiesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leucocytesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(hematocritesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ana8Label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ana7Label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ana9Label, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tcmhLabel)
                    .addComponent(vihLabel)
                    .addComponent(globulesBlancLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(151, 151, 151))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ana6Label1)
                    .addComponent(ana5Label1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vgmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(ccmhLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana1Label1)
                    .addComponent(ana7Label)
                    .addComponent(leucocytesLabel)
                    .addComponent(tcmhLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana2Label1)
                    .addComponent(ana8Label)
                    .addComponent(hematiesLabel)
                    .addComponent(vihLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana3Label1)
                    .addComponent(ana9Label)
                    .addComponent(hemoglobineLabel)
                    .addComponent(globulesBlancLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana4Label1)
                    .addComponent(hematocritesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana5Label1)
                    .addComponent(vgmLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana6Label1)
                    .addComponent(ccmhLabel))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        informationsJPanel.addTab("Résultats", jPanel4);

        globulesBlancLab.setText("Globules blanc :");

        ana6Label.setText("C.C.M.H :");

        ana1Label.setText("Leucocytes :");

        ana2Label.setText("Hématies :");

        ana3Label.setText("Hémoglobine :");

        tcmhLab.setText("T.C.M.H :");

        ana4Label.setText("Hématocrites :");

        vihLab.setText("V.I.H :");

        ana5Label.setText("V.G.M :");

        newAnalyseButton.setText("Nouvelle Analyse");
        newAnalyseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAnalyseButtonActionPerformed(evt);
            }
        });

        urgentRB.setText("Urgent");

        javax.swing.GroupLayout analysesJPanelLayout = new javax.swing.GroupLayout(analysesJPanel);
        analysesJPanel.setLayout(analysesJPanelLayout);
        analysesJPanelLayout.setHorizontalGroup(
            analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analysesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ana6Label)
                        .addComponent(ana5Label)
                        .addComponent(ana4Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ana3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ana2Label)
                    .addComponent(ana1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vgmCB)
                    .addComponent(hematocritesCB)
                    .addComponent(ccmhCB)
                    .addComponent(hemoglobineCB)
                    .addComponent(leucocytesCB)
                    .addComponent(hematiesCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newAnalyseButton)
                    .addGroup(analysesJPanelLayout.createSequentialGroup()
                        .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vihLab, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(globulesBlancLab, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(urgentRB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tcmhLab, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vihCB, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(globulesBlancCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tcmhCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        analysesJPanelLayout.setVerticalGroup(
            analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analysesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tcmhCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(leucocytesCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tcmhLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ana1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hematiesCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vihLab, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vihCB))
                    .addComponent(ana2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(analysesJPanelLayout.createSequentialGroup()
                        .addComponent(globulesBlancCB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(analysesJPanelLayout.createSequentialGroup()
                        .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hemoglobineCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ana3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(globulesBlancLab, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ana4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hematocritesCB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ana5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vgmCB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(analysesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ccmhCB)
                            .addComponent(ana6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
                .addComponent(urgentRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newAnalyseButton))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(analysesJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(analysesJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        informationsJPanel.addTab("Analyses", jPanel1);

        nomLabel.setText("Nom :");

        prenomLabel.setText("Prenom :");

        adresseLabel.setText("Adresse :");

        modifyButton.setText("Modifier");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adresseLabel)
                    .addComponent(prenomLabel)
                    .addComponent(nomLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomTF, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(prenomTF)
                    .addComponent(adresseTF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addComponent(modifyButton)
                .addGap(257, 257, 257))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomLabel)
                    .addComponent(nomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenomLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresseLabel)
                    .addComponent(adresseTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(modifyButton)
                .addContainerGap())
        );

        informationsJPanel.addTab("Informations", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informationsJPanel)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(patientLabel)
                .addGap(247, 247, 247))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informationsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void demandesJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_demandesJListMouseClicked
        int index = demandesJList.locationToIndex(evt.getPoint());
        ListModel dlm = demandesJList.getModel();
        String temp = (String) dlm.getElementAt(index);
        
        String[] parts = temp.split("/");
        
        //Remplisagge des résultats si résultats disponibles.
        a.clear();
        a = analyseSB.getAnalyses(Integer.parseInt(parts[0]));
        
        AffichageAnalyse();
    }//GEN-LAST:event_demandesJListMouseClicked

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        patientSB.updatePatient(patient);
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void newAnalyseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAnalyseButtonActionPerformed
        //Ajout de la demande
        Demande d = new Demande();
        d.setRefMedecin(1);
        d.setRefPatient(patient.getId());
        Calendar cal = Calendar.getInstance();
        d.setDateHeureDemande(cal.getTime());
        d.setUrgent(urgentRB.isSelected());
        urgentRB.setSelected(false);
        
        int refDem = analyseSB.insertDemande(d);
        JOptionPane.showMessageDialog(null, "Demande envoyée ! \n Le numero de référence de demande est : " + refDem);

        JCheckBox[] table = {leucocytesCB,hematiesCB,hemoglobineCB,hematocritesCB,vgmCB,ccmhCB,tcmhCB,vihCB,globulesBlancCB};
        String[] values = {"leucocytes","hematies","hemoglobine","hematocrites","vgm","ccmh","tcmh","vih","globulesblanc"};

        for (int i = 0, tableLength = table.length; i < tableLength; i++) {
            JCheckBox checkBox = table[i];
            if (checkBox.isSelected()){
                listeAnalyses.add(create(values[i]));
                checkBox.setSelected(false);
            }
        }

        for(int i = 0; i < listeAnalyses.size(); i++){
            listeAnalyses.get(i).setRefDemande(refDem);
        }

        //Envoi des analyses
        for(int i = 0; i<listeAnalyses.size(); i++){
            System.out.println(listeAnalyses.get(i).getItem());
            analyseSB.insertAnalyse(listeAnalyses.get(i));
        }
        listeAnalyses.clear();
    }//GEN-LAST:event_newAnalyseButtonActionPerformed

    private Analyses create(String item)
    {
        Analyses temp = new Analyses();
        Calendar cal = Calendar.getInstance();
        temp.setDateAnalyse(cal.getTime());
        temp.setRefPatient(patient.getId());
        temp.setValeur("-");
        temp.setItem(item);
        return temp;
    }
    
    private void AffichageAnalyse(){
        //Reset des labels
        resetLabel();
        //Update des labels
        for(int i = 0; i<a.size(); i++){
            switch(a.get(i).getItem()){
                case "leucocytes" : leucocytesLabel.setText(a.get(i).getValeur());
                break;
                
                case "hematies" : hematiesLabel.setText(a.get(i).getValeur());
                break;
                
                case "hemoglobine" : hemoglobineLabel.setText(a.get(i).getValeur());
                break;
                
                case "hematocrites" : hematocritesLabel.setText(a.get(i).getValeur());
                break;
                
                case "vgm" : vgmLabel.setText(a.get(i).getValeur());
                break;
                
                case "ccmh" : ccmhLabel.setText(a.get(i).getValeur());
            }
        }
    }
    
    private void resetLabel(){
        leucocytesLabel.setText("-");
        hematiesLabel.setText("-");
        hemoglobineLabel.setText("-");
        hematocritesLabel.setText("-");
        vgmLabel.setText("-");
        ccmhLabel.setText("-");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(analysesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(analysesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(analysesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(analysesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new analysesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresseLabel;
    private javax.swing.JTextField adresseTF;
    private javax.swing.JLabel ana1Label;
    private javax.swing.JLabel ana1Label1;
    private javax.swing.JLabel ana2Label;
    private javax.swing.JLabel ana2Label1;
    private javax.swing.JLabel ana3Label;
    private javax.swing.JLabel ana3Label1;
    private javax.swing.JLabel ana4Label;
    private javax.swing.JLabel ana4Label1;
    private javax.swing.JLabel ana5Label;
    private javax.swing.JLabel ana5Label1;
    private javax.swing.JLabel ana6Label;
    private javax.swing.JLabel ana6Label1;
    private javax.swing.JLabel ana7Label;
    private javax.swing.JLabel ana8Label;
    private javax.swing.JLabel ana9Label;
    private javax.swing.JPanel analysesJPanel;
    private javax.swing.JCheckBox ccmhCB;
    private javax.swing.JLabel ccmhLabel;
    private javax.swing.JList<String> demandesJList;
    private javax.swing.JCheckBox globulesBlancCB;
    private javax.swing.JLabel globulesBlancLab;
    private javax.swing.JLabel globulesBlancLabel;
    private javax.swing.JCheckBox hematiesCB;
    private javax.swing.JLabel hematiesLabel;
    private javax.swing.JCheckBox hematocritesCB;
    private javax.swing.JLabel hematocritesLabel;
    private javax.swing.JCheckBox hemoglobineCB;
    private javax.swing.JLabel hemoglobineLabel;
    private javax.swing.JTabbedPane informationsJPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox leucocytesCB;
    private javax.swing.JLabel leucocytesLabel;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton newAnalyseButton;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextField nomTF;
    private javax.swing.JLabel patientLabel;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JTextField prenomTF;
    private javax.swing.JCheckBox tcmhCB;
    private javax.swing.JLabel tcmhLab;
    private javax.swing.JLabel tcmhLabel;
    private javax.swing.JRadioButton urgentRB;
    private javax.swing.JCheckBox vgmCB;
    private javax.swing.JLabel vgmLabel;
    private javax.swing.JCheckBox vihCB;
    private javax.swing.JLabel vihLab;
    private javax.swing.JLabel vihLabel;
    // End of variables declaration//GEN-END:variables
}
